language: rust

rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - cargo test --locked
  - rustup component add rustfmt-preview --toolchain nightly
  - cargo +nightly fmt --all -- --check
