name: build

on:
  pull_request:

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Stable
      run: cargo test --verbose
    - name: Install beta target
      run: rustup update && rustup target add beta
    - name: Test beta
      run: cargo +beta test --verbose
    - name: Install nightly target
      run: rustup target add nightly
    - name: Test nightly
      run: cargo +nightly test --verbose
    - name: Install MSRV target
      run: rustup default 1.56.1
    - name: Test MSRV
      run: cargo test --verbose
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: cargo fmt --all -- --check
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check linting
      - run: cargo clippy -- -D warnings
